### ISSUE TITLE
Saturday January 30th 2016

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#14]
As part of the 2016 plan for Nodeschool London, I am in talks with Inviqa regarding hosting and sponsorship.

They are based on Oxford Street and have capacity to run the current event.

Does anyone have any objections to me getting things moving again?

**Comment by iancrowther** [comment]
@olizilla @alanshaw @ezodude

**Comment by iancrowther** [comment]
Introducting @MarcelloDuarte..

**Comment by imrefazekas** [comment]
You can count on me, 29th Friday is perfect for me.

**Comment by clarkie** [comment]
What time are you talking on the 29th?

**Comment by iancrowther** [comment]
10:00 - 16:00

**Comment by iancrowther** [comment]
damn it... i meant sat the 30th!!!

**Comment by ezodude** [comment]
@iancrowther works for me.

**Comment by cmacrae** [comment]
I'd certainly be interested! Is there any prerequisits/expected experience necessary to come along and join in? :)

**Comment by iancrowther** [comment]
@cmacrae none at all, we welcome everyone

**Comment by iancrowther** [comment]
tickets are live.

https://ti.to/nodeschool/london-january-2016

Mentors!!
submit a PR to add yourself to https://github.com/nodeschool/london/blob/master/mentors.md and ill send you the mentor ticket link
