### ISSUE TITLE
Cleanup Branches

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#20]
We have a separate branch per event so we only use one repo.

Should we create an individual folder instead?

**Comment by ezodude** [comment]
Folders sounds more sane and obvious.

**Comment by iancrowther** [comment]
ok - @ezodude fancy doing a PR to restructure?

**Comment by ezodude** [comment]
@iancrowther I'll get on it. Sorry for the late reply.

**Comment by ezodude** [comment]
@iancrowther I'm going through this. Might be a bunch of PRs for each event branch ;-)
