### ISSUE TITLE
Create learning objectives

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#21]
I want to create a more structured approach to learning to cater for the different ways people learn.

We should have a brainstorming session to kick this off.

When / Where? How about Wednesday 16th December?

**Comment by iancrowther** [comment]
@MarcelloDuarte - do you have anythign to add?

**Comment by jkbits1** [comment]
I teach javascript at various events each month, so I'm happy to come along and contribute.

Any time in mind? I may not be able to stay for long at the lnug party.

**Comment by iancrowther** [comment]
@jkbits1 no problem, just make sure you get a beer from the kitty, you have certainly earned it!

**Comment by ezodude** [comment]
@iancrowther sorry just saw this. Did the brainstorming session go ahead?

**Comment by iancrowther** [comment]
not yet

**Comment by iancrowther** [comment]
if for the host of each event to do independently
