### ISSUE TITLE
Create a shopping list

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#27]
We need to make an online supermarket order for greek/mezze buffet.

We have a budget of around £100

**Comment by iancrowther** [comment]
re-purpose https://github.com/nodeschool/london/blob/master/catering.md

**Comment by iancrowther** [comment]
@ezodude hows thisn coming along? we need to source cating ideally today

**Comment by ezodude** [comment]
@iancrowther No worries. I'll sort it tonight.

**Comment by iancrowther** [comment]
top man, ty

**Comment by ezodude** [comment]
You were right about tesco: only domestic deliveries.

Ocado deliver but they don't have a delivery slot for the 30th of Jan.

**Comment by ezodude** [comment]
Here's the [Shopping List PR](https://github.com/nodeschool/london/pull/36).

**Comment by iancrowther** [comment]
ah I see! any other providers?

**Comment by ezodude** [comment]
@iancrowther its all sorted. 

Just paid for delivery on the 30th using Waitrose. Substituted some items in the shopping list.

Also, when you spend over £100.00 you get £20.00 discount. So, I got an array of biscuits for dessert.

__Final bill -> £87.94__ ... I've forwarded you the receipt.

**Comment by iancrowther** [comment]
https://github.com/nodeschool/london/blob/master/catering.md

@ezodude can you update catering.md and then close the issue

**Comment by iancrowther** [comment]
moving to a gift based model.  if someone want to buy us food then awesome
