### ISSUE TITLE
Schedule tweets running up to the event

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#28]

**Comment by ezodude** [comment]
@iancrowther Scheduled 8 tweets from the 4th till the 25th of Jan. I left the last few days empty for special announcements, like SOLD OUT or more places added.

Have a look and close if all is well.

**Comment by iancrowther** [comment]
perfect - looks good

I created [twitter-templates.md](https://github.com/nodeschool/london/blob/master/twitter-templates.md) so we can re-use/re-purpose in the future

1. How did you decide the times & dates?
2. Are they repeatable? eg 10 days before event
3. Can you categorise the tweets in the md, that way we can create gcal's for "announce new event" and have a selection of templates to choose from.
4. can we create add dates to tweet and optimum times eg tweet template "announce new event" 21 days before date. we can start to explore automating this processes

**Comment by ezodude** [comment]
> How did you decide the times & dates?

* For times, I have tried to use: "just before I start" / "I need a quick break" moments. I have spread these as much as I can too.
* For dates, I spread the tweets as much as possible to avoid looking spammy or desperate.

> Are they repeatable? eg 10 days before event

They are if you ignore the new year-ish ones.

> Can you categorise the tweets in the md, that way we can create gcal's for "announce new event" and have a selection of templates to choose from.

Are we thinking:
* Event first announced.
* Event awareness.
* Event imminent. 

> can we create add dates to tweet and optimum times eg tweet template "announce new event" 21 days before date. we can start to explore automating this processes

Lets gauge traction from each tweet. This should help us discover which have the optimal messaging / times. I'll update the links to use [google URL shortener](https://goo.gl/) to get better analytics.

**Comment by iancrowther** [comment]
Hey - 

- For dates / times I use socialbro.com to anaylse our followers.  it tells you the optimum time to tweet

Tweet types:

### Before Event
Ticket Launch
Ticket Reminder
Thank Speakers
Thank Sponsors
Thank Venue
Ticket Reminder
Sponsorship Request
Call for PR’s (Pull Requests)
Call for Speakers
Event Reminder & Venue Address
Ticket Reminders (if you can’t make it, please cancel)

### Day of Event
Event Reminder
Venue Address

### After Event
Thank Speakers
Next Event
Thank Sponsors
Thank Venue
Next Event Reminder
Call for Feedback

for the google anaylitics.. we need to create a google account for london@nodeschool.io

that way all analytics are owned by the org and accessabel to all orgs
