### ISSUE TITLE
add a collection of photos to the website

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#32]

**Comment by TheBenji** [comment]
Do we have already some cool pics or should we specifically take some nice shots next time?
Also I remember at one nodeschool in the past somebody did some "interviews" with some peeps there as to why they attend and how they like it. What happened to that?

**Comment by iancrowther** [comment]
https://drive.google.com/folderview?id=0B1E3fBFiidMXU0VfTkRIYmhQUWM&usp=sharing

or grab media from Twitter

**Comment by iancrowther** [comment]
@imrefazekas @TheBenji @ezodude any chance we could add some more images?

I have added more previous event photos that we can use:

https://github.com/nodeschool/london/tree/master/resources/events

**Comment by iancrowther** [comment]
this is done and looking great
