### ISSUE TITLE
setup GA account using london@nodeschool.io

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#38]
we should be shortenening links in goo.gl using this acocount also

**Comment by iancrowther** [comment]
were a little blocked on this atm - https://github.com/nodeschool/organizers/issues/313

**Comment by iancrowther** [comment]
have setup a local GA for now and can give permissions to anyone who is interested

**Comment by jpwesselink** [comment]
@iancrowther yes please :D Would be nice to tweet some stats every now and then. 
jpwesselink [ at ] gmail.com

edit: added email address
