### ISSUE TITLE
Hello 2016 from London... It's January!

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/london#43]
Be part of nodeschool globally!

Say hello in this issue and we'll add you to the team..

**Comment by danhayden** [comment]
Hello :)

**Comment by constantincerdan** [comment]
Hello! :D

**Comment by watilde** [comment]
Hello :wave:

**Comment by alanshaw** [comment]
:wave: OH HAI

**Comment by TheBenji** [comment]
Heya :)

**Comment by imrefazekas** [comment]
Hey!

**Comment by pmaudsley** [comment]
Hello NodeSchool!

**Comment by stevenmaudsley** [comment]
Good afternoon

**Comment by ordishs** [comment]
All going well with learnyounode - so far!

**Comment by bernardbaker** [comment]
Hello from Bernard, loving Node School. Great to get together with other developers and see the way that everyone thinks about coding. Social coding rocks..

**Comment by sarchitech** [comment]
Hi, How is everyone doing?

**Comment by jschuur** [comment]
![Oh Hai!](http://www.quickmeme.com/img/6f/6fb2c0cebe2dc1520cf9e416780cefdb9e6bc85b91dc213e20730a29ad875825.jpg)

**Comment by andrewmaudsley** [comment]
Hi!

**Comment by bernardbaker** [comment]
Doing great. The session here at Node School London is really going well. We're having a discussion about finding problems in our code. And I've been learning a lot too.

**Comment by alistairstead** [comment]
:wave: I really enjoyed the session. Next time someone else can be DJ :headphones: :hear_no_evil:

**Comment by ezodude** [comment]
I enjoyed deconstructing async.js - that made my day 👌🏽

**Comment by cataquil** [comment]
well that was suddenly scheduled. wasn't on the calendar in late december was it?

**Comment by iancrowther** [comment]
thank you to everyone who made today possible
