### ISSUE TITLE
when is the next london nodeschool

### ISSUE THREAD

**Issue by cataquil** [nodeschool/london#44]
Is there one in february?

**Comment by iancrowther** [comment]
not currently, however, we are working hard in the background to make it so..  keep an eye on the twitter channel @nodeschool_ldn

**Comment by iancrowther** [comment]
cc @alistairstead

**Comment by alistairstead** [comment]
I would like to host it again at @inviqa. Are there any volunteer mentors?

**Comment by imrefazekas** [comment]
You can count on me.

**Comment by ezodude** [comment]
I'm happy to mentor again.

**Comment by iancrowther** [comment]
http://www.meetup.com/london-nodejs/events/231443634/
