### ISSUE TITLE
Event - Feb 2017

### ISSUE THREAD

**Issue by srounce** [nodeschool/london#46]
There has been other talk (#45) about activity, I thought I'd get the ball rolling toward a next event, and track what's going on (if anything) in one place. That way, everyone can keep on top of what's happening. 

Right now, input is needed regarding dates, venues & mentors. If you have any ideas, comments, requests or questions please share them!

Going forward, I'd really like to get this going monthly, and so am also interested to know who reckons they'd be able to commit to mentoring regularly.

**Date:**
Saturday 25th February → 10:30am - 4pm
 
**Venue:**
Founders & Coders
14 Palmers Rd, London E2 0SY

**List of mentors:**
1. @srounce
2. @alanshaw 
4. @lrlna 
5. @adrianblynch 
6. @dremora  (provisional) 
7. @TheBenji 
8. @lazlojuly

**Comment by alanshaw** [comment]
Either date is fine by me :)

If you're interested and depending on numbers (it would have to be small <20) we could probably do it at our offices in Peckham (on the Saturday date).

**Comment by lrlna** [comment]
oh hello 👋  ! I am yet to come to London's nodeschool event; would totally love to come mentor ^_^

**Comment by srounce** [comment]
@alanshaw That'd be great! This'll be my first time running a chapter event so maybe sub-20 is a good amount to shoot for.

**Comment by lrlna** [comment]
@srounce thanks for adding!

**Comment by adrianblynch** [comment]
Put me down for the weekday and a maybe for the Saturday.

**Comment by koddsson** [comment]
>Going forward, I'd really like to get this going monthly, and so am also interested to know who reckons they'd be able to commit to mentoring regularly.

I'm down for doing this regularly and am available on either day mentioned :)

I don't think it's a optimal venue but I'll ask around if the Cloudflare office can be used for this if we need it.

**Comment by srounce** [comment]
Yo @adrianblynch good to have you onboard! 

---
> I don't think it's a optimal venue but I'll ask around if the CloudFlare office can be used for this if we need it.

@koddsson It's pretty good location-wise, nice and central\*; I'm guessing it's a fairly large space?
I'm curious to know why you think it may be sub-optimal though?

\* Thinking of those in NW London who'll have quite a journey ahead of them/possibly be put off

**Comment by koddsson** [comment]
@srounce I mostly thinking of table space since I think the actual desks are off limits. But I'm probably thinking there are way more people gonna show up then there actually will :D

**Comment by srounce** [comment]
Quick update, we've been offered a use of the Founders & Coders space (awaiting final confirmation) which will allow for about 30-35 and it's in Bethnal Green/Mile End so fairly easy to get to for everyone (Central & District lines nearby, DLR is a 10min bus ride away). It has a mezzanine area\* (≥15 peeps), as well as a projector in the main area which could also be useful.
Map: https://goo.gl/maps/eRf7KcxbaKC2

\* I was thinking of doing a "Hello World" group workshopper for all the super-fresh newbies, then rotate mentors throughout the day as they progress? Might be nicer for them so there's less cross-chatter/easier for them to focus.

@koddsson That's a good point, NodeSchool might be a bit uncomfortable sitting on the floor 😁

**Comment by koddsson** [comment]
@srounce I'm talking to the office person and figuring this stuff out. Normally we don't do weekend meetups. We do have tables to use but my concern was just about space on those. I'll continue the conversation with the office person and maybe we can do it here next time :)

**Comment by lazlojuly** [comment]
Hi, I am happy to mentor too!

**Comment by koddsson** [comment]
Hey @srounce. I hate to do this but something came up and I won't be able to make it on the 25th 😭

**Comment by srounce** [comment]
@koddsson That's a shame dude. Hopefully will see you next time! 🤞

**Comment by lazlojuly** [comment]
@srounce Do we have an update on the venue? Also, I was unsure if I can make it but now both dates are good for me.

**Comment by Dremora** [comment]
@srounce if I'm mentoring, should I keep myself as attendee on the event page?
@lazlojuly it would be great to see you there!

**Comment by srounce** [comment]
Yes please @Dremora, just so I can keep track of the total a bit easier. Look forward to seeing you tomorrow!

**Comment by TheBenji** [comment]
I can't make the whole day but I'll probably drop by in the afternoon :)

**Comment by srounce** [comment]
Okay, today's the day. Look forward to seeing you lot at the venue for 10:00 (10:30 is fine, but having some time beforehand so mentors can meet and greet first might be nice). I'm a little concerned we won't have enough mentors (we'll probably be fine), so if you know anyone that would be up for last-minute mentoring please get in touch with them. 👍
